"""
gcode.py
Generates G-code from the adaptive slicer output.

Each layer uses the parameters decided by the RL + Sika 733 physics:
  - F (feedrate) from per-layer print_speed
  - E (extrusion) scaled by extrusion_multiplier
  - Layer height from slicer
  - Interlayer wait (G4 dwell)

Output is standard RepRap-compatible G-code, readable by any 3DCP controller.
"""

from typing import List, Optional
from optimizer import LayerParams
from geometry import Segment, Layer
import math


def toolpath_to_gcode(
    toolpath:     List[Layer],
    layer_params: List["LayerParams"],
    printer_name: str        = "Custom 3DCP Printer",
    uses_e_axis:  bool       = True,
    nozzle_diam_mm: float    = 25.0,
    comment_level: int       = 1,    # 0=none, 1=section headers, 2=verbose
) -> str:
    """
    Convert ordered toolpath + per-layer params to G-code string.

    Coordinate system:
      X, Y = horizontal plane (mm)
      Z    = vertical (layer height, mm)
      E    = extrusion (mm of filament equivalent — for concrete this controls pump RPM)
      F    = feedrate (mm/min)
    """
    lines: List[str] = []

    def c(text: str) -> str:
        """Format a comment line."""
        return f"; {text}" if comment_level >= 1 else ""

    # ── Header ────────────────────────────────────────────────────────────────

    lines += [
        c("=" * 60),
        c("AutoBuild AI — Adaptive 3DCP G-code"),
        c(f"Material: Sikacrete-733 W 3D"),
        c(f"Printer:  {printer_name}"),
        c(f"Nozzle:   {nozzle_diam_mm} mm"),
        c(f"Layers:   {len(toolpath)}"),
        c("Generated by AutoBuild AI RL Slicer"),
        c("=" * 60),
        "",
        "; === INITIALISE ===",
        "G21         ; units: millimetres",
        "G90         ; absolute positioning",
        "M83         ; relative extrusion" if uses_e_axis else "; pump-controlled extrusion",
        "G92 E0      ; reset extrusion counter",
        "G1 F1000    ; safe starting feedrate",
        "",
    ]

    e_total = 0.0    # cumulative extrusion in mm (proxy for pump volume)

    for layer_idx, (layer_segs, lp) in enumerate(zip(toolpath, layer_params)):

        if not layer_segs:
            lines += [
                c(f"Layer {layer_idx + 1}/{len(toolpath)} — empty, skip"),
                "",
            ]
            continue

        # Per-layer params
        z_mm        = lp.z_height_m    * 1000          # m → mm
        speed_mm_s  = lp.print_speed_mm_s
        speed_mm_min = speed_mm_s * 60                  # mm/s → mm/min
        ext_mult     = lp.extrusion_multiplier
        wait_ms      = int(lp.interlayer_wait_s * 1000)
        temp_c       = lp.weather_snapshot.get("temperature", 20.0)
        risk         = lp.risk_score

        bead_area_mm2 = nozzle_diam_mm * (lp.layer_height_m * 1000)   # width × height

        lines += [
            c("-" * 50),
            c(f"Layer {layer_idx + 1}/{len(toolpath)}"),
            c(f"  Z:        {z_mm:.1f} mm"),
            c(f"  Speed:    {speed_mm_s:.1f} mm/s  ({speed_mm_min:.0f} mm/min)"),
            c(f"  Ext mult: {ext_mult:.3f}"),
            c(f"  Temp:     {temp_c:.1f}°C  |  Risk: {risk:.1f}/100"),
            c(f"  Pot life remaining: {lp.pot_life_remaining_min:.1f} min"),
            c(f"  Interlayer wait: {lp.interlayer_wait_s:.1f}s"),
        ]

        # Lift to layer height
        lines += [
            f"G0 Z{z_mm:.3f}  {c('raise to layer height')}",
        ]

        # Travel to first segment start (no extrusion)
        first_seg = layer_segs[0]
        x0 = first_seg[0][0] * 1000   # m → mm
        y0 = first_seg[0][1] * 1000
        lines += [
            f"G0 X{x0:.3f} Y{y0:.3f} F3000  {c('travel to layer start')}",
        ]

        # Print each segment
        for seg_idx, seg in enumerate(layer_segs):
            x_start = seg[0][0] * 1000
            y_start = seg[0][1] * 1000
            x_end   = seg[1][0] * 1000
            y_end   = seg[1][1] * 1000

            seg_len_mm = math.hypot(x_end - x_start, y_end - y_start)

            # Travel move if not continuous from previous segment
            if seg_idx > 0:
                prev_end = layer_segs[seg_idx - 1][1]
                gap_mm   = math.hypot(
                    x_start - prev_end[0] * 1000,
                    y_start - prev_end[1] * 1000,
                )
                if gap_mm > 1.0:   # > 1mm gap → travel move
                    lines.append(
                        f"G0 X{x_start:.3f} Y{y_start:.3f} F3000  {c('travel')}"
                    )

            # Extrusion amount: volume / filament cross-section equivalent
            if uses_e_axis:
                e_amount = (seg_len_mm * bead_area_mm2 * ext_mult) / (math.pi * (1.75/2)**2)
                e_total += e_amount
                e_str = f" E{e_total:.4f}"
            else:
                e_str = ""   # pump-controlled: no E axis

            lines.append(
                f"G1 X{x_end:.3f} Y{y_end:.3f} F{speed_mm_min:.0f}{e_str}  "
                f"{c(f'seg {seg_idx + 1}') if comment_level >= 2 else ''}"
            )

        # Interlayer wait (Sika 733 minimum interlayer time)
        if wait_ms > 0 and layer_idx < len(toolpath) - 1:
            lines += [
                f"G4 P{wait_ms}  {c(f'wait {lp.interlayer_wait_s:.1f}s for layer bond')}",
            ]

        lines.append("")

    # ── Footer ────────────────────────────────────────────────────────────────

    lines += [
        c("=" * 60),
        c("Print complete"),
        "G0 Z100   ; raise nozzle",
        "M84       ; disable motors",
        c("End of file"),
    ]

    return "\n".join(lines)


def format_print_time(seconds: float) -> str:
    """Format seconds into human-readable time string."""
    if seconds < 60:
        return f"{int(seconds)}s"
    elif seconds < 3600:
        m = int(seconds // 60)
        s = int(seconds % 60)
        return f"{m}m {s}s"
    else:
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        return f"{h}h {m}m"